-- Historial de partidas terminadas (victoria o equipo caido) para el ranking.
CREATE TABLE match_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building         VARCHAR(16)  NOT NULL,
    victory          BOOLEAN      NOT NULL,
    kinder_reached   INTEGER      NOT NULL,
    duration_seconds BIGINT       NOT NULL,
    player_count     INTEGER      NOT NULL,
    played_at        TIMESTAMP    NOT NULL
);

CREATE TABLE match_player (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id         BIGINT       NOT NULL REFERENCES match_record (id),
    role             VARCHAR(32)  NOT NULL,
    kills            INTEGER      NOT NULL,
    missions         INTEGER      NOT NULL,
    garavitos_earned INTEGER      NOT NULL,
    damage_taken     INTEGER      NOT NULL,
    revives          INTEGER      NOT NULL,
    downs            INTEGER      NOT NULL
);

CREATE INDEX idx_match_record_ranking ON match_record (building, victory, kinder_reached, duration_seconds);
